//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keutmann.SharePoint.WSPBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Keutmann.SharePoint.WSPBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;*** WSPBuilder Diamond Directive File
        ///; 
        ///;
        ///.OPTION EXPLICIT                  	; Generate errors on variable typos
        ///;
        ///.Set CabinetNameTemplate={0}	  	; The name of the WSP file
        ///.set DiskDirectoryTemplate=CDROM  	; All cabinets go in a single directory
        ///.Set CompressionType=MSZIP	    	; 
        ///.Set Cabinet=on				        ; 
        ///.Set Compress=on			        ;
        ///.Set DiskDirectory1=.          	    ; Use the specified directory for the output CAB file 
        ///;
        ///;*** Disable size limits for wsp (cab) files ;
        ///;
        ///.Set Cabine [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DDFTemplate {
            get {
                return ResourceManager.GetString("DDFTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /12
        ////12/ADMISAPI
        ////12/BIN
        ////12/BIN/1033
        ////12/CONFIG
        ////12/CONFIG/ADMINBIN
        ////12/CONFIG/AdminResources
        ////12/CONFIG/BIN
        ////12/CONFIG/Resources
        ////12/CONFIG/UPGRADE
        ////12/HCCab
        ////12/HCCab/1033
        ////12/Help
        ////12/Help/1033
        ////12/ISAPI
        ////12/ISAPI/HELP
        ////12/ISAPI/HELP/1033
        ////12/ISAPI/HELP/1033/STS
        ////12/ISAPI/HELP/1033/STS/IMAGES
        ////12/ISAPI/_VTI_ADM
        ////12/ISAPI/_VTI_AUT
        ////12/LOGS
        ////12/Resources
        ////12/TEMPLATE
        ////12/TEMPLATE/1030
        ////12/TEMPLATE/1030/XML
        ////12/TEMPLATE/1033
        ////12/TEMPLATE/1033/STS
        ////12/TEMPLATE/1033/STS/DOCTEMP
        //// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Folders12 {
            get {
                return ResourceManager.GetString("Folders12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                         &lt;PermissionSet
        ///                                class=&quot;NamedPermissionSet&quot;
        ///                                version=&quot;1&quot;
        ///                                Unrestricted=&quot;true&quot;
        ///                        /&gt;
        ///.
        /// </summary>
        internal static string PermissionSetFull {
            get {
                return ResourceManager.GetString("PermissionSetFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PermissionSet class=&quot;NamedPermissionSet&quot; version=&quot;1&quot; Name=&quot;SPRestricted&quot;&gt;
        ///              &lt;IPermission class=&quot;AspNetHostingPermission&quot; version=&quot;1&quot; Level=&quot;Medium&quot; /&gt;
        ///              &lt;IPermission class=&quot;DnsPermission&quot; version=&quot;1&quot; Unrestricted=&quot;true&quot; /&gt;
        ///              &lt;IPermission class=&quot;EnvironmentPermission&quot; version=&quot;1&quot; Read=&quot;TEMP;TMP;USERNAME;OS;COMPUTERNAME&quot; /&gt;
        ///              &lt;IPermission class=&quot;FileIOPermission&quot; version=&quot;1&quot; Read=&quot;$AppDir$&quot; Write=&quot;$AppDir$&quot; Append=&quot;$AppDir$&quot; PathDiscovery=&quot;$AppDir$&quot; /&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PermissionSetMedium {
            get {
                return ResourceManager.GetString("PermissionSetMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                         &lt;PermissionSet
        ///                                class=&quot;NamedPermissionSet&quot;
        ///                                version=&quot;1&quot;
        ///                                Name=&quot;SPRestricted&quot;&gt;
        ///                            &lt;IPermission 
        ///                                    class=&quot;AspNetHostingPermission&quot;
        ///                                    version=&quot;1&quot;
        ///                                    Level=&quot;Minimal&quot;
        ///                            /&gt;
        ///                            &lt;IPermission 
        ///                         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PermissionSetMinimal {
            get {
                return ResourceManager.GetString("PermissionSetMinimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                         &lt;PermissionSet      
        ///                                class=&quot;NamedPermissionSet&quot;
        ///                                version=&quot;1&quot;
        ///						/&gt;
        ///.
        /// </summary>
        internal static string PermissionSetNone {
            get {
                return ResourceManager.GetString("PermissionSetNone", resourceCulture);
            }
        }
    }
}
